name: fresh_keeper
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0
supabase_flutter: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Piazolla
      fonts:
      - asset: fonts/Piazzolla-VariableFont_opsz,wght.ttf
      - asset: fonts/Piazzolla-Bold.ttf
        weight: 500
